### ISSUE TITLE
Lack of code

### ISSUE THREAD

**Issue by zyc1314** [fanci-dga-detection/fanci#3]
The code of the part of intelligence is missing, could you upload it again?

**Comment by sMau** [comment]
Dear zyc1314,

First, sorry for the late answer.
I am sorry but everything what was created related to our paper at [1] is already in this project here and it is especially meant to be a prototypic implementation. Nonetheless it is fully functional and in case you are in possession of adequate data you can train models for DGA detection very easily. 

There is ongoing work, which also includes a real full-blown implementation of an intelligence module. As this is also again part of academic work and is planned to be published at an academic conference we want to wait until everything is cut and dried. We hope for your understanding.

Best regards,
Samuel

[1] https://www.usenix.org/conference/usenixsecurity18/presentation/schuppen
